---创建用户表
CREATE TABLE SYS_USER
(
  USER_ID VARCHAR2(64 BYTE) NOT NULL
, USER_NAME VARCHAR2(255 BYTE)
, PASSWORD VARCHAR2(50 BYTE)
, LOGIN_NAME VARCHAR2(50 BYTE)
, EMAIL VARCHAR2(50 BYTE)
, PHONE VARCHAR2(20 BYTE)
, CREATE_DATE DATE
, UPDATE_DATE DATE
, DEL_FLAG CHAR(1 BYTE)
, REMARKS VARCHAR2(1024 BYTE)
, EXPIRED_DATE DATE
, PICK_URL VARCHAR2(256 BYTE)
, CREATE_ID VARCHAR2(64 BYTE)
, UPDATE_ID VARCHAR2(64 BYTE)
, CONSTRAINT SYS_USER_PK PRIMARY KEY
  (
    USER_ID
  )
) ;

COMMENT ON COLUMN SYS_USER.USER_ID IS '用户ID';

COMMENT ON COLUMN SYS_USER.USER_NAME IS '用户名';

COMMENT ON COLUMN SYS_USER.PASSWORD IS '密码';

COMMENT ON COLUMN SYS_USER.LOGIN_NAME IS '登录名';

COMMENT ON COLUMN SYS_USER.EMAIL IS '邮箱';

COMMENT ON COLUMN SYS_USER.PHONE IS '电话';

COMMENT ON COLUMN SYS_USER.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN SYS_USER.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN SYS_USER.DEL_FLAG IS '删除标记';

COMMENT ON COLUMN SYS_USER.REMARKS IS '备注';

COMMENT ON COLUMN SYS_USER.EXPIRED_DATE IS '过期时间';

COMMENT ON COLUMN SYS_USER.PICK_URL IS '头像';

COMMENT ON COLUMN SYS_USER.CREATE_ID IS '创建人';

COMMENT ON COLUMN SYS_USER.UPDATE_ID IS '更新人';



CREATE TABLE SYS_MENU
(
  MENU_ID VARCHAR2(64 BYTE) NOT NULL
, PARENT_ID VARCHAR2(64 BYTE)
, MENU_NAME VARCHAR2(100 BYTE)
, MENU_URL VARCHAR2(100 BYTE)
, MENU_TYPE VARCHAR2(20 BYTE)
, IS_SHOW NUMBER(*, 0)
, MENU_SORT NUMBER
, MENU_ICON VARCHAR2(20 BYTE)
, CREATE_DATE DATE
, UPDATE_DATE DATE
, DEL_FLAG CHAR(1 BYTE)
, PERMISSION VARCHAR2(128 BYTE)
, CREATE_ID VARCHAR2(64 BYTE)
, UPDATE_ID VARCHAR2(64 BYTE)
, CONSTRAINT SYS_MENU_PK PRIMARY KEY
  (
    MENU_ID
  )
) ;

COMMENT ON COLUMN SYS_MENU.MENU_ID IS '菜单唯一标识';

COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '父级编号';

COMMENT ON COLUMN SYS_MENU.MENU_NAME IS '菜单名称';

COMMENT ON COLUMN SYS_MENU.MENU_URL IS '菜单Url';

COMMENT ON COLUMN SYS_MENU.MENU_TYPE IS '菜单类型';

COMMENT ON COLUMN SYS_MENU.IS_SHOW IS '是否显示 0：隐藏 1：显示';

COMMENT ON COLUMN SYS_MENU.MENU_SORT IS '菜单排序';

COMMENT ON COLUMN SYS_MENU.MENU_ICON IS '菜单图标';

COMMENT ON COLUMN SYS_MENU.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN SYS_MENU.UPDATE_DATE IS '更新时间';

COMMENT ON COLUMN SYS_MENU.DEL_FLAG IS '是否有效';

COMMENT ON COLUMN SYS_MENU.PERMISSION IS '权限字符串';

COMMENT ON COLUMN SYS_MENU.CREATE_ID IS '创建人';

COMMENT ON COLUMN SYS_MENU.UPDATE_ID IS '更新人';


----角色表
CREATE TABLE SYS_ROLE
(
  ROLE_ID VARCHAR2(64 BYTE) NOT NULL
, ROLE VARCHAR2(128 BYTE)
, ROLE_NAME VARCHAR2(128 BYTE)
, AVAILABLE NUMBER(*, 0)
, CREATE_DATE DATE
, UPDATE_DATE DATE
, DEL_FLAG CHAR(1 BYTE)
, DESCRIPTION VARCHAR2(1024 BYTE)
, CREATE_ID VARCHAR2(64 BYTE)
, UPDATE_ID VARCHAR2(64 BYTE)
, CONSTRAINT SYS_ROLE_PK PRIMARY KEY
  (
    ROLE_ID
  )
) ;

COMMENT ON COLUMN SYS_ROLE.ROLE_ID IS '角色唯一标识';

COMMENT ON COLUMN SYS_ROLE.ROLE IS '角色标识';

COMMENT ON COLUMN SYS_ROLE.ROLE_NAME IS '角色名称';

COMMENT ON COLUMN SYS_ROLE.AVAILABLE IS '是否可用';

COMMENT ON COLUMN SYS_ROLE.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN SYS_ROLE.UPDATE_DATE IS '更新日期';

COMMENT ON COLUMN SYS_ROLE.DEL_FLAG IS '删除标记';

COMMENT ON COLUMN SYS_ROLE.DESCRIPTION IS '角色描述';

COMMENT ON COLUMN SYS_ROLE.CREATE_ID IS '创建人';

COMMENT ON COLUMN SYS_ROLE.UPDATE_ID IS '更新人';



----角色用户关联表
CREATE TABLE SYS_USER_ROLE
(
  USER_ID VARCHAR2(64 BYTE) NOT NULL
, ROLE_ID VARCHAR2(64 BYTE) NOT NULL
, CONSTRAINT SYS_USER_ROLE_PK PRIMARY KEY
  (
    USER_ID
  , ROLE_ID
  )
  USING INDEX
  (
      CREATE UNIQUE INDEX SYS_USER_ROLE_PK ON SYS_USER_ROLE (USER_ID ASC, ROLE_ID ASC)
  )
) ;

COMMENT ON COLUMN SYS_USER_ROLE.USER_ID IS '用户ID';

COMMENT ON COLUMN SYS_USER_ROLE.ROLE_ID IS '角色ID';

---部门信息表
CREATE TABLE SYS_DEPT
(
  DEPT_ID VARCHAR2(64 BYTE) NOT NULL
, PARENT_ID VARCHAR2(64 BYTE)
, DEPT_LEVEL CHAR(1 BYTE)
, DEPT_CODE VARCHAR2(64 BYTE)
, DEPT_NAME VARCHAR2(128 BYTE)
, DEPT_SORT NUMBER(*, 0)
, CREATE_DATE DATE
, UPDATE_DATE DATE
, DEL_FLAG CHAR(1 BYTE)
, CREATE_ID VARCHAR2(64 BYTE)
, UPDATE_ID VARCHAR2(64 BYTE)
, CONSTRAINT SYS_DEPT_PK PRIMARY KEY
  (
    DEPT_ID
  )
) ;

COMMENT ON COLUMN SYS_DEPT.DEPT_ID IS '部门主键';

COMMENT ON COLUMN SYS_DEPT.PARENT_ID IS '部门父级编号';

COMMENT ON COLUMN SYS_DEPT.DEPT_LEVEL IS '部门层级';

COMMENT ON COLUMN SYS_DEPT.DEPT_CODE IS '部门编号';

COMMENT ON COLUMN SYS_DEPT.DEPT_NAME IS '部门名称';

COMMENT ON COLUMN SYS_DEPT.DEPT_SORT IS '排序';

COMMENT ON COLUMN SYS_DEPT.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN SYS_DEPT.UPDATE_DATE IS '更新日期';

COMMENT ON COLUMN SYS_DEPT.DEL_FLAG IS '是否有效标志';

COMMENT ON COLUMN SYS_DEPT.CREATE_ID IS '创建人';

COMMENT ON COLUMN SYS_DEPT.UPDATE_ID IS '更新人';


---部门用户关联表
CREATE TABLE SYS_USER_DEPT
(
  USER_ID VARCHAR2(64) NOT NULL
, DEPT_ID VARCHAR2(64) NOT NULL
, CONSTRAINT SYS_USER_DEPT_PK PRIMARY KEY
  (
    DEPT_ID
  , USER_ID
  )
  ENABLE
);

COMMENT ON COLUMN SYS_USER_DEPT.USER_ID IS '用户ID';

COMMENT ON COLUMN SYS_USER_DEPT.DEPT_ID IS '部门Id';

drop table sys_log;

CREATE TABLE SYS_LOG
(
  LOG_ID VARCHAR2(64 BYTE) NOT NULL
, USER_NAME VARCHAR2(50 BYTE)
, HOST VARCHAR2(20 BYTE)
, ACTION VARCHAR2(255 BYTE)
, EVENT VARCHAR2(1024 BYTE)
, INSERT_TIME TIMESTAMP(6)
, METHOD VARCHAR2(128 BYTE)
, PARAMS CLOB
, CONSTRAINT SYS_LOG_PK PRIMARY KEY
  (
    LOG_ID
  )
) ;

COMMENT ON COLUMN SYS_LOG.LOG_ID IS '日志主键';

COMMENT ON COLUMN SYS_LOG.USER_NAME IS '用户名';

COMMENT ON COLUMN SYS_LOG.HOST IS '访问主机';

COMMENT ON COLUMN SYS_LOG.ACTION IS '行为';

COMMENT ON COLUMN SYS_LOG.EVENT IS '事件描述';

COMMENT ON COLUMN SYS_LOG.INSERT_TIME IS '操作时间';

COMMENT ON COLUMN SYS_LOG.METHOD IS '方法';

COMMENT ON COLUMN SYS_LOG.PARAMS IS '参数';
