-- 创建用户表
CREATE TABLE SYS_USER
(
  USER_ID VARCHAR(64) NOT NULL COMMENT '用户ID'
, USER_NAME VARCHAR(255) COMMENT '用户名'
, PASSWORD VARCHAR(50) COMMENT '密码'
, LOGIN_NAME VARCHAR(50) COMMENT '登录名'
, EMAIL VARCHAR(50) COMMENT '邮箱'
, PHONE VARCHAR(20) COMMENT '电话'
, CREATE_DATE DATE COMMENT '创建时间'
, UPDATE_DATE DATE COMMENT '更新时间'
, DEL_FLAG CHAR(1) COMMENT '删除标记'
, REMARKS VARCHAR(1024) COMMENT '备注'
, EXPIRED_DATE DATE COMMENT '过期时间'
, PICK_URL VARCHAR(256) COMMENT '头像'
, CREATE_ID VARCHAR(64) COMMENT '创建人'
, UPDATE_ID VARCHAR(64) COMMENT '更新人'
, CONSTRAINT SYS_USER_PK PRIMARY KEY
  (
    USER_ID
  )
) ;
-- 菜单表
CREATE TABLE SYS_MENU
(
  MENU_ID VARCHAR(64) NOT NULL COMMENT '菜单唯一标识'
, PARENT_ID VARCHAR(64) COMMENT '父级编号'
, MENU_NAME VARCHAR(100) COMMENT '菜单名称'
, MENU_URL VARCHAR(100) COMMENT '菜单Url'
, MENU_TYPE VARCHAR(20) COMMENT '菜单类型'
, IS_SHOW numeric COMMENT '是否显示 0：隐藏 1：显示'
, MENU_SORT numeric COMMENT '菜单排序'
, MENU_ICON VARCHAR(20)  COMMENT '菜单图标'
, CREATE_DATE DATE COMMENT '创建时间'
, UPDATE_DATE DATE COMMENT '更新时间'
, DEL_FLAG CHAR(1) COMMENT '删除标记'
, PERMISSION VARCHAR(128) COMMENT '权限字符串'
, CREATE_ID VARCHAR(64) COMMENT '创建人'
, UPDATE_ID VARCHAR(64) COMMENT '更新人'
, CONSTRAINT SYS_MENU_PK PRIMARY KEY
  (
    MENU_ID
  )
) ;



-- -角色表
CREATE TABLE SYS_ROLE
(
  ROLE_ID VARCHAR(64) NOT NULL COMMENT  '角色唯一标识'
, ROLE VARCHAR(128) COMMENT '角色标识'
, ROLE_NAME VARCHAR(128) COMMENT '角色名称'
, AVAILABLE numeric COMMENT '是否可用'
, CREATE_DATE DATE COMMENT '创建时间'
, UPDATE_DATE DATE COMMENT '更新时间'
, DEL_FLAG CHAR(1) COMMENT '删除标记'
, DESCRIPTION VARCHAR(1024) COMMENT '角色描述'
, CREATE_ID VARCHAR(64) COMMENT '创建人'
, UPDATE_ID VARCHAR(64) COMMENT '更新人'
, CONSTRAINT SYS_ROLE_PK PRIMARY KEY
  (
    ROLE_ID
  )
) ;


-- 角色菜单关联表
CREATE TABLE SYS_ROLE_MENU
(
  ROLE_ID VARCHAR(64) NOT NULL COMMENT '角色ID'
, MENU_ID VARCHAR(64) NOT NULL COMMENT '菜单Id'
, CONSTRAINT SYS_ROLE_MENU_PK PRIMARY KEY
  (
    ROLE_ID
  , MENU_ID
  )
);

-- -角色用户关联表
CREATE TABLE SYS_USER_ROLE
(
  USER_ID VARCHAR(64) NOT NULL COMMENT '用户ID'
, ROLE_ID VARCHAR(64) NOT NULL COMMENT '角色ID'
, CONSTRAINT SYS_USER_ROLE_PK PRIMARY KEY
  (
    USER_ID
  , ROLE_ID
  )
) ;

-- 部门信息表
CREATE TABLE SYS_DEPT
(
  DEPT_ID VARCHAR(64) NOT NULL COMMENT '部门主键'
, PARENT_ID VARCHAR(64) COMMENT '部门父级编号'
, DEPT_LEVEL CHAR(1) COMMENT '部门层级'
, DEPT_CODE VARCHAR(64) COMMENT '部门编号'
, DEPT_NAME VARCHAR(128) COMMENT '部门名称'
, DEPT_SORT numeric COMMENT '排序'
, CREATE_DATE DATE COMMENT '创建时间'
, UPDATE_DATE DATE COMMENT '更新时间'
, DEL_FLAG CHAR(1) COMMENT '删除标记'
, CREATE_ID VARCHAR(64) COMMENT '创建人'
, UPDATE_ID VARCHAR(64) COMMENT '更新人'
, CONSTRAINT SYS_DEPT_PK PRIMARY KEY
  (
    DEPT_ID
  )
) ;


-- 部门用户关联表
CREATE TABLE SYS_USER_DEPT
(
  USER_ID VARCHAR(64) NOT NULL COMMENT '用户ID'
, DEPT_ID VARCHAR(64) NOT NULL COMMENT '部门Id'
, CONSTRAINT SYS_USER_DEPT_PK PRIMARY KEY
  (
    DEPT_ID
  , USER_ID
  )
);



-- 日志表
CREATE TABLE SYS_LOG
(
  LOG_ID VARCHAR(64) NOT NULL COMMENT '日志主键'
, USER_NAME VARCHAR(50) COMMENT '用户名'
, HOST VARCHAR(20) COMMENT '访问主机'
, ACTION VARCHAR(255) COMMENT '行为'
, EVENT VARCHAR(1024) COMMENT '事件描述'
, INSERT_TIME TIMESTAMP(6) COMMENT '操作时间'
, METHOD VARCHAR(128) COMMENT '方法'
, PARAMS text COMMENT '参数'
, CONSTRAINT SYS_LOG_PK PRIMARY KEY
  (
    LOG_ID
  )
) ;

-- 文件管理
CREATE TABLE SYS_FILE
(
  FILE_ID VARCHAR(64) NOT NULL COMMENT '文件ID'
, FILE_PATH VARCHAR(255) COMMENT '文件路径'
, FILE_TYPE VARCHAR(128) COMMENT '文件类型'
, FILE_NAME VARCHAR(128) COMMENT '文件名'
, FILE_SIZE numeric COMMENT '文件大小'
, CREATE_DATE DATE COMMENT '创建时间'
, UPDATE_DATE DATE COMMENT '更新时间'
, DEL_FLAG CHAR(1) COMMENT '删除标记'
, CREATE_ID VARCHAR(64) COMMENT '创建人'
, UPDATE_ID VARCHAR(64) COMMENT '更新人'
, CONSTRAINT SYS_FILE_PK PRIMARY KEY
  (
    FILE_ID
  )
) ;

