
package com.tao.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.jws.WebService(name = "WebService", targetNamespace = "http://webService.hai.tao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://webService.hai.tao.com/", className = "com.tao.webservice.client.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://webService.hai.tao.com/", className = "com.tao.webservice.client.GetUserResponse")
    @Action(input = "http://webService.hai.tao.com/WebService/getUserRequest", output = "http://webService.hai.tao.com/WebService/getUserResponse")
    public String getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
